# This is the default base file to config env and command
# Notice that chaincode is executed inside docker in default net mode
# https://github.com/yeasy/docker-compose-files

# Depends on the yeasy/hyperledger-peer:noops image

# See https://github.com/hyperledger/fabric/blob/master/docs/dev-setup/devnet-setup.md#using-consensus-plugin for more details.

version: '2'

services:
  vp:
    image: yeasy/hyperledger-peer:noops
    restart: unless-stopped
    labels:
      - monitor=true
      - hyperledger=true
      - com.docker.swarm.reschedule-policy=["on-node-failure"]
    hostname: vp0
    container_name: ${COMPOSE_PROJECT_NAME}_vp0
    environment:
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_NETWORKID=${PEER_NETWORKID}
      - CORE_LOGGING_LEVEL=${LOGGING_LEVEL_CLUSTER} #critical, error, warning, notice, info, debug
      # The following section enables bpft consensus
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=noops  # noops, pbft, sieve
      - CORE_PEER_ID=vp
      - CORE_NOOPS_BLOCK_TIMEOUT=10
      - CORE_VM_ENDPOINT=${DAEMON_URL}
    expose:
      - "30303"
      - "30304"
      - "31315"
    ports:
      - "${API_PORT}:5000"
    #volumes: # docker.sock is mapped as the default CORE_VM_ENDPOINT
    #  - /var/run/docker.sock:/var/run/docker.sock
    mem_limit: 500000000
    memswap_limit: 1000000000
    cpu_quota: 50000
    command: peer node start
    logging:
      driver: syslog
      options:
        syslog-address: ${SYSLOG_SERVER}
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"

networks:
  default:
    external:
      name: ${CLUSTER_NETWORK}