# this is an example of the PoolManager API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: PoolManager API
  description: PoolManager API to manage cluster
  contact:
    name: Baohua Yang
    url: https://github.rtp.raleigh.ibm.com/blockchain/poolmanager
    email: baohyang@cn.ibm.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "1.0.0"
# the domain of the service
host: 9.186.100.88:80
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /clusters:
    get:
      summary: A list of all clusters
      description: |
        The Clusters endpoint returns information about all existing clusters.
        The response includes the display name
        and other details about each cluster, and lists the clusters in the
        proper display order.
      parameters:
        - name: daemon_url
          in: query
          description: Filter clusters with specific daemon_url.
          required: false
          type: string
        - name: user_id
          in: query
          description: Filter clusters with specific user_id.
          required: false
          type: string
      tags:
        - Clusters
      responses:
        200:
          description: An array of clusters
          schema:
            type: array
            items:
              $ref: '#/definitions/Cluster'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Cluster:
    type: object
    required: [uuid, user_id, api_url]
    properties:
      uuid:
        type: string
        description: Unique identifier representing a specific cluster.
      user_id:
        type: string
        description: User id who owns this cluster, empty by default
      api_url:
        type: string
        description: Cluster REST URL representing the cluster.
      host_id:
        type: string
        description: Which host the cluster is at.
      display_name:
        type: string
        description: Display name of cluster.
  Error:
    type: object
    required: [code]
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
